WebApplication2/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.MultipleModelInOneView;

using PagedList;


namespace WebApplication2.Controllers
{
    public class IndexController : Controller
    {

        //// GET: Index

        //====================================
        //Tạo 1 đối tượng chứa toàn bộ CSDL từ dbQLBANLKDT
        db2DataContext data = new db2DataContext();


        private List<SANPHAM> LaySanPhamMoi(int count)
        {
            //Sắp xếp giảm dần theo ngày cập nhật, lấy "count" dòng đầu
            return data.SANPHAMs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }

        private List<SANPHAM> LaySanPhamTheoLoai(int id, int count)
        {
            //Sắp xếp giảm dần theo ngày cập nhật, lấy "count" dòng đầu
            return data.SANPHAMs.Where(a => a.LOAISANPHAM.MaLoai == id).Take(count).ToList();
        }

        private List<LOAISANPHAM> LayTatCaLoaiSP()
        {
            return data.LOAISANPHAMs.ToList();
        }

        private List<SANPHAM> LaySPTimKiem(string searchString)
        {
            List<SANPHAM> sanphams = data.SANPHAMs.OrderByDescending(n => n.Ngaycapnhat).ToList();
            if(!string.IsNullOrEmpty(searchString))
            {
                sanphams = (sanphams.Where(n => n.TenSP.Contains(searchString) || n.LOAISANPHAM.TenLoai.Contains(searchString))).ToList();
            }

            return sanphams;
        }

        public ActionResult Index()
        {
            //Phải fix cái này lại nghe =========================== Để từ từ fix
            List<SANPHAM> sanphams = new List<SANPHAM>();
            //Lấy 5 sản phẩm mới nhất
            sanphams = LaySanPhamMoi(5);

            //Lấy Ảnh (Đã Optimize)
            List<ANHPHU> anhphus = new List<ANHPHU>();
            foreach (SANPHAM sp in sanphams)
            {
                //var tempAnh = from ap in data.ANHPHUs where ap.MaSP == sp.MaSP select ap;
                var tempAnh = data.ANHPHUs.First(n => n.MaSP == sp.MaSP);

                anhphus.Add(tempAnh);
            }

            ViewData["anhbia"] = anhphus;


            return View(sanphams);
        }

        //chi tiet san pham
        public ActionResult Details(int id)
        {
            Detail_Mota detail_Mota = new Detail_Mota();

            var sanPham = from sp in data.SANPHAMs
                          where sp.MaSP == id
                          select sp;
            detail_Mota.SANPHAM = sanPham.Single();

            String[] separator = { "<br>" }; //Chữ để tách
            detail_Mota.MotaStrings = detail_Mota.SANPHAM.Mota.Split(separator, StringSplitOptions.RemoveEmptyEntries);

            //Lấy Ảnh (Đã Optimize)
            List<ANHPHU> anhphus = data.ANHPHUs.Where(a => a.MaSP == id).ToList();

            ViewData["anhbia"] = anhphus;

            return View(detail_Mota);
        }

        public ActionResult ListSPDanhMuc(int id , int ? page)
        {
            //Page List
            int pageSize = 8;
            //Tạo biến số trang
            int pageNum = (page ?? 1);

            

            var sanPham = from loaiSp in data.LOAISANPHAMs
                          from sp in data.SANPHAMs
                          where loaiSp.MaDM == id && sp.MaLoai == loaiSp.MaLoai
                          select sp;

            //Lấy Ảnh (Đã Optimize)
            List<ANHPHU> anhphus = new List<ANHPHU>();
            foreach(SANPHAM sp in sanPham.ToPagedList(pageNum, pageSize).ToList())
            {
                //var tempAnh = from ap in data.ANHPHUs where ap.MaSP == sp.MaSP select ap;
                var tempAnh = data.ANHPHUs.First(n => n.MaSP == sp.MaSP);

                anhphus.Add(tempAnh);
            }

            ViewData["anhbia"] = anhphus;

            //Lấy Title
            DANHMUC tempDM = data.DANHMUCs.SingleOrDefault(n => n.MaDM == id);
            ViewBag.Name = tempDM.TenDanhMuc;

            return View(sanPham.ToPagedList(pageNum, pageSize));
        }

        public ActionResult ListSPLoai(int id, int? page)
        {
            //Page List
            int pageSize = 8;
            //Tạo biến số trang
            int pageNum = (page ?? 1);

            var sanPham = from loaiSp in data.LOAISANPHAMs
                          from sp in data.SANPHAMs
                          where loaiSp.MaLoai == id && sp.MaLoai == loaiSp.MaLoai
                          select sp;

            //Lấy Ảnh (Đã Optimize)
            List<ANHPHU> anhphus = new List<ANHPHU>();
            foreach (SANPHAM sp in sanPham.ToPagedList(pageNum, pageSize).ToList())
            {
                //var tempAnh = from ap in data.ANHPHUs where ap.MaSP == sp.MaSP select ap;
                var tempAnh = data.ANHPHUs.First(n => n.MaSP == sp.MaSP);

                anhphus.Add(tempAnh);
            }

            ViewData["anhbia"] = anhphus;

            //Lấy Title
            LOAISANPHAM tempLoai = data.LOAISANPHAMs.SingleOrDefault(n => n.MaLoai == id);
            ViewBag.Name = tempLoai.DANHMUC.TenDanhMuc;
            ViewBag.NameLoai = tempLoai.TenLoai;

            return View(sanPham.ToPagedList(pageNum, pageSize));
        }


        //partial view
        public ActionResult Chude()

        {
            ModelDanhMucs modelDanhMucs = new ModelDanhMucs();

            modelDanhMucs.DANHMUCs = from cd in data.DANHMUCs select cd;
            modelDanhMucs.LOAISANPHAMs = from lsp in data.LOAISANPHAMs select lsp;



            return PartialView(modelDanhMucs);

        }

        public ActionResult ChudeonMB()

        {

            ModelDanhMucs modelDanhMucsMb = new ModelDanhMucs();

            modelDanhMucsMb.DANHMUCs = from cd in data.DANHMUCs select cd;
            modelDanhMucsMb.LOAISANPHAMs = from lsp in data.LOAISANPHAMs select lsp;



            return PartialView(modelDanhMucsMb);

        }

        //Partial View Các Sản Phẩm Cùng Loại
        public ActionResult subProduct(int id, int count)
        {
            var sanphams = LaySanPhamTheoLoai(id, count);

            var rnd = new Random();
            var sanphamsRandom = sanphams.OrderBy(item => rnd.Next());

            //Lấy Ảnh (Đã Optimize)
            List<ANHPHU> anhphus = new List<ANHPHU>();
            foreach (SANPHAM sp in sanphamsRandom)
            {
                //var tempAnh = from ap in data.ANHPHUs where ap.MaSP == sp.MaSP select ap;
                var tempAnh = data.ANHPHUs.First(n => n.MaSP == sp.MaSP);

                anhphus.Add(tempAnh);
            }

            ViewData["anhbia"] = anhphus;

            return PartialView(sanphamsRandom);
        }

        //Partial View Kênh Youtube
        public ActionResult kenhYoutube(int count)
        {
            var videoYt = data.Videos.Take(count).ToList();

            var rnd = new Random();
            var kenhytRandom = videoYt.OrderBy(item => rnd.Next());


            return PartialView(kenhytRandom);
        }

        //Partial View Thanh Tìm Kiếm
        public ActionResult timKiem()
        {
            return PartialView();
        }


        public ActionResult TimKiemSP(string searchString, int? page)
        {
            searchString = searchString.ToUpper();

            //Page List
            int pageSize = 8;
            //Tạo biến số trang
            int pageNum = (page ?? 1);

            var sanPham = LaySPTimKiem(searchString);

            //Lấy Ảnh (Đã Optimize)
            List<ANHPHU> anhphus = new List<ANHPHU>();
            foreach (SANPHAM sp in sanPham.ToPagedList(pageNum, pageSize).ToList())
            {
                //var tempAnh = from ap in data.ANHPHUs where ap.MaSP == sp.MaSP select ap;
                var tempAnh = data.ANHPHUs.First(n => n.MaSP == sp.MaSP);

                anhphus.Add(tempAnh);
            }

            ViewData["anhbia"] = anhphus;

            //Kiểm tra xem có tìm thấy sản phẩm nào không
            if(sanPham.Count() > 0)
            {
                ViewBag.KetQua = "Kết quả tìm kiếm cho từ khóa: ";
            }
            else
            {
                ViewBag.KetQua = "Không tìm thấy kết quả tìm kiếm cho từ khóa: ";
            }

            ViewBag.TuKhoa =  searchString;

            return View(sanPham.ToPagedList(pageNum, pageSize));

        }
        public ActionResult Video(int ? page)
        {
            var listVideo = data.Videos.OrderByDescending(n => n.NgayCapNhat).ToList();

            //Page List
            int pageSize = 8;
            //Tạo biến số trang
            int pageNum = (page ?? 1);

            return View(listVideo.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult ChinhSachVanChuyen()
        {
            return View();
        }
        public ActionResult ChinhSachBaoHanh()
        {
            return View();
        }
    }

}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication2/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw=="
          crossorigin="anonymous" />
    <link href="~/Content/menuMB.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" ">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle boxa" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Admin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                @Html.Action("timKiem", "Admin")
            </div>

        </div>
    </div>
    <div class="box">
        <a href="@Url.Action("Sanpham", "Admin")"><i class="fa fa-address-card-o" aria-hidden="true"></i> Quản lý sản phẩm</a>
        <a href="@Url.Action("Themmoisp", "Admin")"><i class="fa fa-address-card-o" aria-hidden="true"></i> Tạo mới sản phẩm</a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>



   




    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/app.js"></script>
    <script>
        const box = document.querySelector('.box');
        const toggle = document.querySelector('.boxa');
        toggle.addEventListener("click", function (e) {

            box.classList.toggle('active');
        }
        )
       
    </script>
</body>
</html>

WebApplication2/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/StyleSheet1.css" rel="stylesheet" />

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw=="
          crossorigin="anonymous" />


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600&display=swap" rel="stylesheet">


    <link href="~/Content/menuMB.css" rel="stylesheet" />
</head>
<body>

    <div class="header">
        <div class="top-nav">
            <div class="container">
                <div class="top-bar">
                    <ul class="social">
                        <li><a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href=""><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
                        <li><a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a></li>

                    </ul>
                    @*  click de ra form dang nhap *@
                <div class="user">
                    @Html.Action("loginPartial", "User")
                </div>
                </div>
            </div>
        </div>


        <div id="inner-nav">
            <div class="container">
                <div class="inner-nav">
                    @* nút menu *@
                    <div class="ham">
                        <span class="line"></span>
                        <span class="line line2"></span>
                        <span class="line"></span>

                    </div>
                    <a href="@Url.Action("Index", "Index")" class="logo">
                        <img height="70px" width="70px" src="@Url.Content("~/img/DNK_Icon.png") " />
                    </a>
                    
                    @Html.Action("timKiem", "Index")

                    <div class="header-btn">
                        @Html.Action("GiohangPartical", "Giohang")
                    </div>
                </div>
            </div>
        </div>


        <div id="mega-menu">
            <div class="container">
                <div class="mega-menu">
                    <div class="mega-title"> <i class="fa fa-bars" aria-hidden="true"></i>Danh mục sản phẩm</div>
                    <ul class="shop-if">
                        <li><a href="@Url.Action("Video","Index", new { page = 1 })">Video</a></li>
                        <li><a href="#">Hướng dẫn mua hàng</a></li>
                        <li><a href="@Url.Action("ChinhSachVanChuyen","Index")">Chính sách vận chuyển</a></li>
                        <li><a href="@Url.Action("ChinhSachBaoHanh","Index")">Chính sách bảo hành </a></li>
                        <li><a href="@Url.Action("Contact","Index")">Liên hệ</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </div>


    <div>
        @RenderBody()
    </div>
    <div class="footer" style="margin-top:100px; padding-bottom:50px;">
        <div class="container">
            <div class="ft-top mb-10">
                <div class="ft-top-left">
                    <p>Địa chỉ: 475A Điện Biên Phủ, Thành phố Hồ Chí Minh  </p>
                    <p>Số điện thoại :028 5445 2222 </p>
                    <p>Địa chỉ email : truyenthong@hutech.edu.vn</p>
                </div>
                <div class="ft-top-right">
                    <ul>
                        <li><a href="https://www.facebook.com/hutechuniversity" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-git" aria-hidden="true"></i></a></li>
                        <li><a href="https://www.youtube.com/channel/UClWYcK8eeRxFTNYR4QI0L_g" target="_blank"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="ft-bot">
                <div class="row">
                    <div class="col-lg-6 col-10">
                        <div class="map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.125120810274!2d106.71230301432061!3d10.801727892304358!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528a459cb43ab%3A0x6c3d29d370b52a7e!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBDw7RuZyBuZ2jhu4cgVFAuSENNIC0gSFVURUNI!5e0!3m2!1svi!2s!4v1649514296293!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="backToTop">
        <i class="fa fa-angle-up" aria-hidden="true"></i>
    </div>
    @* menu trên mobile gom partialview *@
    @Html.Action("ChudeonMB", "Index")


    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/app.js"></script>
    <script>
        if (window.innerWidth > 760) {
            const texts = document.querySelectorAll(".product a.namePro");

            [...texts].forEach(item => item.addEventListener("mouseenter", function (e) {

                const title = e.target.textContent;
                const tooltipDiv = document.createElement("div");
                tooltipDiv.className = "tooltip-text";
                tooltipDiv.textContent = title;
                document.body.appendChild(tooltipDiv);
                const cords = event.target.getBoundingClientRect();
                const { top, left, width } = cords;
                const tooltipHeight = tooltipDiv.offsetHeight;
                const triangleHeight = 20;
                tooltipDiv.style.left = `${left - width / 4}px`;
                tooltipDiv.style.top = `${top - tooltipHeight - triangleHeight}px`;
            }));
            [...texts].forEach(item => item.addEventListener("mouseleave", function (e) {
                const tooltip = document.querySelector(".tooltip-text");
                if (!tooltip) return;
                tooltip.parentNode.removeChild(tooltip);
            }));



            //lightbox
            const imgs = document.querySelectorAll('.detail-imgs img');
            [...imgs].forEach(item => item.addEventListener('click', function (e) {
                const image = e.target.getAttribute("src");
                const template = `
   <div class="lightbox">
     <div class="lightbox-content">
       <i class="fa fa-angle-left lightbox-prev"></i>
       <img
         src="${image}"
         alt=""
         class="lightbox-image"
       />
       <i class="fa fa-angle-right lightbox-next"></i>
     </div>
   </div>`;
                document.body.insertAdjacentHTML("beforeend", template);
            }))
            let index = 0;
            document.addEventListener("click", function (e) {
                const lightImage = document.querySelector(".lightbox-image");
                if (!lightImage) return;
                let lightSrc = lightImage.getAttribute("src");
                index = [...imgs].findIndex(
                    (item) => item.getAttribute("src") === lightSrc
                );
                if (e.target.matches(".lightbox")) {
                    e.target.parentNode.removeChild(e.target);
                } else if (e.target.matches(".lightbox-next")) {
                    index = index + 1;
                    if (index > imgs.length - 1) {
                        index = 0;
                    }
                    displayLightImage(lightImage, index);
                } else if (e.target.matches(".lightbox-prev")) {
                    index = index - 1;
                    if (index < 0) {
                        index = imgs.length - 1;
                    }
                    displayLightImage(lightImage, index);
                }
            });

            function displayLightImage(lightImage, index) {
                const newSrc = [...imgs][index].getAttribute("src");
                lightImage.setAttribute("src", newSrc);
            }



        } else {
            window.addEventListener('scroll', function (e) {
                const menu = document.querySelector('.menu-mb');
                const ham = document.querySelector('.ham');
                if (menu.classList.contains("active")) {
                    menu.classList.remove('active');
                    ham.classList.remove('active-ham');
                }

            })
        }
          
        
    </script>
    
</body>
</html>